### ISSUE TITLE
Error when Deleting Files and Re-Adding Them

### ISSUE THREAD

**Issue by FoxMcloud5655** [brandon3055/ProjectIntelligence#6]
When deleting a file and then trying to add the same file back to the documentation, the file "ModDocs/[modid]/[version]/structure/lang/[language].json" is not updated to reflect the deletion, resulting in an error when trying to add it back.  It states that the file already exists, when in reality, it is not.

**Comment by brandon3055** [comment]
So is it just me? ore does it also take 10 years to reload from disk when the editor is open?
I only ask because i figure thats something you would have mentioned by now.

**Comment by FoxMcloud5655** [comment]
Just you?  I have my repository on an SSD, and it reloads in about half a second.  I haven't had any problems with the editor speed-wise!  Really love how easy it is to use, too.

**Comment by brandon3055** [comment]
Hmm.. the storage drive should not have any effect because the problematic code was just restoring the state of the tree. Its possible the issue was amplified because i am running in dev. In any case its fixed now. Went from 30~ seconds to 18ms xD. 
Was a combination of some inefficient stream code and manipulating the UI from the game thread instead of the AWT thread. 

This is what the UI was doing for me before the fix.
https://ss.brandon3055.com/d6904
After the fix i had to figure out why it wasn't reloading at all now... Turns out it was reloading. It was just instantaneous xD.

**Comment by brandon3055** [comment]
I cant wait to completely re write this UI in JavaFX! 
I only recently started messing with JavaFX but it is SOO much better! Just need to find the time to do it.

**Comment by FoxMcloud5655** [comment]
Ah, I see.  I don't pretend to understand any of the code without first looking at it :P
Good luck with JavaFX, and I hope it'll be even better than what you already have!
