### ISSUE TITLE
Can't close the insctruction screen once open... The X Button doesn't do anything

### ISSUE THREAD

**Issue by Fireztonez** [brandon3055/ProjectIntelligence#8]
Hello,
I just add Project Intelligence to my modpack, and I see the little PI Icon on an EnderIO machine, so  I click on the button and it open the interface with somes information (Not really usefull I think for me, but this is not the point...). I try to close that interface, but when I click on the X button, I ear a little click, but, nothing appen.

I think this is probably a compatibility issue with another mod adding buttons in the same corner...

In that corner I have an Arrow Button from JEI, Buttons from NEI, and somes times button from FTB Utilities (Any mods try to put stuff there there!!).
![half_screen_gui_X_button](https://user-images.githubusercontent.com/19277301/56089816-ccf82380-5e66-11e9-8aa9-24b96a19c102.png)

The 2 button on the right work great, but and if I reduce the window when I'm in Full Screen mode, I can click the X button, but, it just return exactly like in the screen shot, it just never really close that... In the same place, I have the favorites from JEI, and I whant to be able to use that feature, but, this is just impossible with that open...

Sure, when I quit the machine interface, PI disapear, but, if I return on the SAG Mill, it always reopen that (Why??)

**Comment by brandon3055** [comment]
I think i fixed the issue but i would like you to confirm if possible before i push to curse.
http://chickenbones.net/maven/com/brandon3055/projectintelligence/ProjectIntelligence/1.12.2-1.0.5.20/ProjectIntelligence-1.12.2-1.0.5.20-universal.jar
You should at least be able to press the close button now.

**Comment by Fireztonez** [comment]
Ok I just download your new pre-version, I test and I will tell you if the issue is fixed!

**Comment by Fireztonez** [comment]
The Issue is exacly the same, but I have look test to see if the issue if from JEI or NEI, and look like the issue came from the NotEnougItems buttons (in that case the garbage can I think...). If I disabled NotEnoughItems I can click without issue on the X button.

So, I suggest to add that mod in your test instance, question of test yourself before pushing the update.

**Comment by Twisted-Code** [comment]
> 
> 
> The Issue is exacly the same, but I have look test to see if the issue if from JEI or NEI, and look like the issue came from the NotEnougItems buttons (in that case the garbage can I think...). If I disabled NotEnoughItems I can click without issue on the X button.
> 
> So, I suggest to add that mod in your test instance, question of test yourself before pushing the update.

I'm guessing English is not your first language (which is fine of course; the Internet is international and I hold no bias). What did you mean when you said " question of test yourself"?

**Comment by brandon3055** [comment]
Ok so let me explain whats going on here. 
The actual size and placement of the info window is not controlled by me. That's controlled by the mod implementing it which in this case is EnderIO. But there is nothing wrong with EnderIO's implementation because the PI info window is designed to render on top of and take priority over anything else it happens to conflict with. 

This issue is specifically related to NEI. The NEI buttons are coded rather poorly and as a result they take priority over PI's buttons and there is nothing i can do to work around them.

Im sure @covers1624 will correct me if im wrong but given the current state of NEI development this issue probably isn't likely to be resolved any time soon.

**Comment by Twisted-Code** [comment]
Brandon, I'm having the problem with not being able to click the close button on PI 1.0.8.25, with Enderio just like this. If version 1.0.5.20 fixed it, something broke it thereafter. Can we reopen this?

**Comment by brandon3055** [comment]
@macks2008 Do you have NEI installed? If so its an issue with NEI that can not be fixed from my end. If your not using NEI then i need your mod list / mod pack.

**Comment by Twisted-Code** [comment]
I am using NEI; I just thought you had some sort of duct tape/voodoo to work around it or something based on your comment from April 14. Has the issue been reported to NEI's tracker? I'll go bug them if so, because I'd like to see this fixed so the mod becomes, well, more usable.
Side note, I noticed a few of EnderIO's basic machines, including SAG Mill and Alloy Smelter implement PI but don't seem to have any documentation currently. Does the documentation exist and it's just not being loaded for some reason (I remember the curseforge overview mentioning something about the backend being under development), or do you still need a PR for that? Because I'd like to help out if possible. Both of those machines, in particular, are simple enough that the documentation doesn't need to be particularly lengthy, so I was surprised it's not available currently.

**Comment by brandon3055** [comment]
@covers1624 is aware of the issue with NEI but i think NEI is just dead at this point. I'm not sure if he plans to bring it back.
I'm not sure what's up with EIO. I'm pretty sure that documentation was implemented. I will take a look at it when i get a chance.

**Comment by Twisted-Code** [comment]
rip...

**Comment by brandon3055** [comment]
Ok so pages do exist for those machines they just show the recipe and... That's about it. Which means the documentation is working. It's just incomplete.
